[book]
authors = ["Danny Ben Shitrit"]
language = "en"
multilingual = false
src = "src"
title = "Jobly Documentation"

[build]
build-dir = "docs"
create-missing = false

[output.html]
default-theme = "ayu"

[output.html.fold]
enable = true

[output.html.playpen]
editable = true